### ISSUE TITLE
Parse error on Bash for Windows

### ISSUE THREAD

**Issue by joelvaneenwyk** [joelvaneenwyk/language84#1]
./84_stable: 2: ./84_stable: Syntax error: ")" unexpected

**Comment by ebb** [comment]
Is it on_programs_changed that's failing?

I made a branch that gets rid of that script: see simpler-build branch on https://github.com/ebb/language84

**Comment by joelvaneenwyk** [comment]
That's very likely the issue -- I'll take a look at your updated branch this weekend. Thanks! :)

**Comment by joelvaneenwyk** [comment]
This is more interesting than I thought it would be. I merged in your build system changes and that did **not** fix it. And again, just to be clear, this all works fine in a full Linux VM and only a problem in Bash for Windows (aka. Windows Subsystem for Linux). It seems it's a combination of two issues:

1. Using -s to strip symbols is something that Bash for Windows does not like. If I try to run the executable directly I get "-bash: ./84_stable: cannot execute binary file: Exec format error". Removing -s gives me a working executable that outputs "usage: 84 [-x] <program>"
2. The parser does not support CRLF. Trying to compile 84.84 gives me:

```
jvaneenwyk@jovaneen-razer:~/Projects/language84$ ./84_stable -x 84
84.84:1: Unexpected token while parsing statement.
Begin {
       ^
```
Looking through scan.84 perhaps it's a simple fix to scan_character?

**Comment by ebb** [comment]
Admittedly, running on other platforms is not something I've put any time into. Maybe now is a good time to start thinking about that.

The first point there is a mystery to me but, as for the second one, I think a good place to add support for carriage return would be in the "whitespace" function within scan.84. There are two places in that function where it checks for newline. Maybe it's enough to add checks for CR in there.

**Comment by ebb** [comment]
Hmm. I realize that supporting CR is a fun case because the scanner doesn't know about the \r escape sequence. So you could either use the integer value directly (13, I think) or you could make a two-stage change: adding support in scan_character first, building that support into the compiler, then use the upgraded compiler to build a new one with the \r escape code used in "whitespace".

**Comment by joelvaneenwyk** [comment]
Thanks for the tips on how to fix this! It is now working inside Bash for Windows and successfully parses/compiles the 'hello world' sample. ^_^

**Comment by joelvaneenwyk** [comment]
Latest commit fixes this. @ebb, take a look at latest commits and let me know if I did anything egregious.
